# Generated by Django 2.2 on 2022-01-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=150)),
                ('ingredients', models.CharField(max_length=500)),
                ('cooking_method', models.CharField(max_length=1000)),
            ],
        ),
    ]
